### ISSUE TITLE
Remove `updateBrowsers` and `bootSnippet`

### ISSUE THREAD

**Issue by stewSquared** [lihaoyi/workbench-example-app#41]
See conversation in gitter here: https://gitter.im/lihaoyi/workbench-example-app?at=582137e7e097df757583323e

> `updateBrowsers` is a holdover from the days when the `packageJS` blob was 20mb and took chrome 10-20s to parse and execute

**Comment by lihaoyi** [comment]
🔥 🔥 🔥

**Comment by stewSquared** [comment]
resolved in #42 #43 #44
